name: Latex Check before Merge

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'Relazione/**'
      - 'Relazione'

jobs:
  preparation:
    name: Controllo errori
    runs-on: ubuntu-latest
    steps:
    - name: Preparo i file del PR
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 4
    - name: Inizio la compilazione
      id: compilation
      uses: xu-cheng/latex-action@v2
      with:
        root_file: "*.tex"
        glob_root_file: true
        working_directory: "Relazione/"
        args: "-pdf -file-line-error -halt-on-error"
    - name: check files
      run: |
        cd Relazione
        ls -la
    - name: Upload della preview
      if: steps.compilation.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
          name: Preview PDF
          path: Relazione/main.pdf
          
  build:
    name: Creo la Release
    if: github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Creo la zip Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        path: 'Relazione/*'
        filename: 'release.zip'
        exclusions: '*.git* README.md .editorconfig'
    - name: Download della preview
      uses: actions/download-artifact@v3
      id: download
      with:
        name: Preview PDF
    - name: Download Path
      run: echo ${{steps.download.outputs.download-path}}
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Release Relazione"
        files: |
          *.zip
